config/routes.rb
OnlineTutoringApp::Application.routes.draw do
  resources :annoncements
  resources :advertisements
  root to: "static_pages#home"

  get "static_pages/about"
  resources :users do
    member do
      get :friends, :requests, :blocked_users, :my_rooms
    end
    resources :rooms
  end

  match '/users/:id/messages', to: 'users#messages', via: :get
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :requests, only: [:create, :destroy]
  resources :messages, only: :create
  resources :blocked_relationships, only: [:create,:destroy]
  resources :comments, only: [:create, :update, :destroy]
  
  match '/refresh', to: 'sessions#refresh', via: :get

  match '/signup', to: 'users#new'
  match '/users/:id/full_role', to: 'users#full_role', via: :post, as: :full_role_user
  match '/signin', to: 'sessions#new', via: :get
  match '/signin', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/search', to: 'search_contents#new', as: :new_search
  match '/search_contents', to: 'search_contents#create', via: :get, as: :search
  match '/requests/delete_request', to: 'requests#delete_request', via: :post
  match '/rooms/delete_by_student', to: 'rooms#delete_by_student', via: :post
  match '/rooms/:id/new_line', to: 'rooms#new_line'
  match '/rooms/:id/clear', to: 'rooms#clear'
  match '/rooms/:id/messages', to: 'rooms#message', as: :room_new_message

  match '/chat/users/new', to: 'chat#new_user', via: :get
  match '/chat/users/:id', to: 'chat#remove_user' 
  match '/chat/messages', to: 'chat#get_conversations'
  match '/chat/messages/:id', to: 'chat#get_conversation'
  match '/chat/messages/:id/read', to: 'messages#read', via: :get

end

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  def home
    @annoncements = Annoncement.order("created_at DESC").limit(3)
    @advertisements = Advertisement.order("created_at DESC").limit(2)
    @top_teachers = User.find_by_sql("SELECT * FROM users JOIN comments ON users.id = comments.teacher_id group by users.id order by count(*) DESC limit 5")
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
# -*- encoding : utf-8 -*-
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
  <div class="container">
  <div class="theme">
    <h1>良师</h1>
    <h2>在线</h2>
    <img alt="pic2" src="/assets/res/pic2.png" width="281" height="245"/> <img alt="pic2" src="/assets/res/pic1.png" width="281" height="245"/> <img id="subtitle" src="/assets/res/subtitle.png"/>
    <div id="clear"></div>
  </div>
  <div class="search">
    <%= form_tag(search_path, :method => 'get') do %>
      <%= text_field_tag :content, @content %>
      <%= hidden_field_tag :gender, 2 %>
      <%= hidden_field_tag :role, 0 %>
      <%= submit_tag "", class: "button_search" %>
    <% end%>
  </div>
  <div class="bulletin">
    <h1>公告栏</h1>
    <table>
      <% @annoncements.each do |annoncement| %>
        <tr>
          <td class="title"><%= link_to annoncement.title, annoncement %>
            <p id="time"><%= annoncement.created_at.localtime.to_s(:db) %></p>
            <p><%= annoncement.content %></p>
          </td>
        </tr>
      <% end %>
    </table>
    <%= link_to "查看更多", annoncements_path %>
  </div>
  <div class="intro"> <img src="/assets/res/selfintro.png"/>
    <table>
      <% @advertisements.each do |ad| %>
        <tr>
          <td style="white-space: normal;">
            <div id="single">
              <h2>来自:</h2>
              <h2><%= ad.user.name %></h2>
              <div id="clear"/>
              <p><%= ad.content %></p>
            </div>
          </td>
        </tr>
      <% end %>
      <tr>
        <td><%= link_to "查看更多", advertisements_path %></td>
      </tr>
    </table>
  </div>
  <div id="clear"></div>
  <div class="teacher">
    <h2>热门讲师</h2>
    <% @top_teachers.each do |teacher| %>
      <%= link_to gravatar_for(teacher, size: 137), teacher %>
    <% end %>
  </div>
</div>
</div>
<footer>
	<div class="navibar">
	© 2013 online tutoring app group. All rights reserved. 
</div>
</footer>