config/routes.rb
OnlineTutoringApp::Application.routes.draw do
  resources :annoncements
  resources :advertisements
  root to: "static_pages#home"

  get "static_pages/about"
  resources :users do
    member do
      get :friends, :requests, :blocked_users, :my_rooms
    end
    resources :rooms
  end

  match '/users/:id/messages', to: 'users#messages', via: :get
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :requests, only: [:create, :destroy]
  resources :messages, only: :create
  resources :blocked_relationships, only: [:create,:destroy]
  resources :comments, only: [:create, :update, :destroy]
  
  match '/refresh', to: 'sessions#refresh', via: :get

  match '/signup', to: 'users#new'
  match '/users/:id/full_role', to: 'users#full_role', via: :post, as: :full_role_user
  match '/signin', to: 'sessions#new', via: :get
  match '/signin', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/search', to: 'search_contents#new', as: :new_search
  match '/search_contents', to: 'search_contents#create', via: :get, as: :search
  match '/requests/delete_request', to: 'requests#delete_request', via: :post
  match '/rooms/delete_by_student', to: 'rooms#delete_by_student', via: :post
  match '/rooms/:id/new_line', to: 'rooms#new_line'
  match '/rooms/:id/clear', to: 'rooms#clear'
  match '/rooms/:id/messages', to: 'rooms#message', as: :room_new_message

  match '/chat/users/new', to: 'chat#new_user', via: :get
  match '/chat/users/:id', to: 'chat#remove_user' 
  match '/chat/messages', to: 'chat#get_conversations'
  match '/chat/messages/:id', to: 'chat#get_conversation'
  match '/chat/messages/:id/read', to: 'messages#read', via: :get

end

app/models/user.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  email           :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)      not null
#  role            :integer          default(1), not null
#  gender          :integer
#  district_id     :integer
#  description     :string(255)
#  degree_id       :integer
#  teacher_visible :boolean          default(TRUE), not null
#  student_visible :boolean          default(TRUE), not null
#  video_url       :string(255)
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation,
                  :gender, :district_id, :description, :role,
                  :student_visible, :teacher_visible, :degree_id,
                  :student_subject_ids, :teacher_subject_ids,
                  :video_id
  attr_accessor :updating_password

  has_many :student_relationships
  has_many :student_subjects, through: :student_relationships, source: :subject
  has_many :teacher_relationships
  has_many :teacher_subjects, through: :teacher_relationships, source: :subject
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "receiver_id"
  belongs_to :district
  belongs_to :degree
  
#as a student
  has_many :relationships, foreign_key: "student_id", dependent: :destroy
  has_many :teachers, through: :relationships
  has_many :room_student_relationships, foreign_key: "student_id", dependent: :destroy
  has_many :my_rooms, through: :room_student_relationships, source: :room
#as a teacher
  has_many :reverse_relationships, foreign_key: "teacher_id",class_name:"Relationship", dependent: :destroy
  has_many :students, through: :reverse_relationships
  has_many :rooms

  has_many :requests, foreign_key:"receiver_id", dependent: :destroy

  has_many :blocked_relationships,dependent: :destroy
  has_many :blocked_users, through: :blocked_relationships, source: :blocked_user
  has_many :advertisements,dependent: :destroy
  #as teacher
  has_many :comments, foreign_key: "teacher_id", dependent: :destroy
  
  scope :teacher_order, select("users.id, count(comments.id) as comments_count").joins(:comments).order("comments_count DESC")
  
  accepts_nested_attributes_for :student_subjects

  before_save { |user| user.email = email.downcase }

  validates :role, presence: true
  validates :name, presence: true, length: { maximum: 20 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: { minimum: 7 },
            if: :should_validate_password?
  validates :password_confirmation, presence: true,
            if: :should_validate_password?
  validate :correct_video_format

  VALID_VIDEO_URL_REGEX = /\A(http:\/\/)?v\.youku\.com\/v_show\/id_(\w{13}).+\.html/
  VALID_VIDEO_ID_REGEX = /\A\w{13}\z/

  def correct_video_format
    return if self.video_id.blank?
    return if VALID_VIDEO_ID_REGEX =~ self.video_id
    if VALID_VIDEO_URL_REGEX =~ self.video_id
      self.video_id = $2
    else
      errors.add(:video_id, "格式不正确")
    end
  end

  def self.find_by_email_and_role(email, role)
    return nil unless [0, 1].include?(role)
    user = User.find_by_email(email)
    if user && (user.role == role || user.role == 2)
      return user
    end
    return nil
  end

  def should_validate_password?
    updating_password || new_record?
  end

  def full_role?
    self.role == 2
  end

  def is_student?
    self.role == 1 || self.role == 2 
  end

  def is_teacher?
    self.role == 0 || self.role == 2
  end

  def online?
    last_seen = $redis.zscore("online-users", self.id)
    return last_seen && last_seen >= 1.minute.ago.to_i
  end

  def has_blocked?(user)
    return nil if user.nil? 
    self.blocked_users.include?(user)
  end

#create 
  def have_been_friends?(other_user,current_student)
    if current_student
      self.relationships.find_by_teacher_id(other_user.id)
    else 
      self.reverse_relationships.find_by_student_id(other_user.id)
    end
  end

  def set_to_be_friends!(other_user, current_student)
    if current_student
      self.relationships.create!(teacher_id: other_user.id)
    else
      self.reverse_relationships.create!(student_id: other_user.id)
    end
  end

  def set_not_to_be_friends!(other_user, current_student)
    if current_student
      self.relationships.find_by_teacher_id(other_user.id).destroy
    else
      self.reverse_relationships.find_by_student_id(other_user.id).destroy
    end
  end

  def have_send_add_request?(other_user, current_student)
    if current_student
      other_user.requests.find_by_sender_id_and_kind(self.id, 1)
    else
      other_user.requests.find_by_sender_id_and_kind(self.id, 2)
    end
  end
  
  def update_send_add_request!(other_user, content, current_student)
    if current_student
      other_user.requests.find_by_sender_id_and_kind(self.id, 1).update_attributes(read: false, content: content)
    else
      other_user.requests.find_by_sender_id_and_kind(self.id, 2).update_attributes(read: false, content: content)
    end
  end

  def send_add_request!(other_user, content, current_student)
    if current_student
      other_user.requests.create!(sender_id: self.id, kind: 1, read: false, content: content)
    else
      other_user.requests.create!(sender_id: self.id, kind: 2, read: false, content: content)
    end
  end

  def have_add_request?(other_user, current_student)
    if current_student
      self.requests.find_by_sender_id_and_kind(other_user.id, 2)
    else
      self.requests.find_by_sender_id_and_kind(other_user.id, 1)
    end
  end

  def send_accept_request!(other_user, current_student)
    if current_student
      other_user.create_normal_request!(self.id, 3, "同意了你的请求")
    else
      other_user.create_normal_request!(self.id, 4, "同意了你的请求")
    end
  end
  def send_refuse_request!(other_user, current_student)
    if current_student
      other_user.create_normal_request!(self.id, 3, "拒绝了你的请求")
    else
      other_user.create_normal_request!(self.id, 4, "拒绝了你的请求")
    end
  end

  def delete_add_request!(other_user, current_student)
    if current_student
      self.requests.find_by_sender_id_and_kind(other_user.id, 2).destroy
    else
      self.requests.find_by_sender_id_and_kind(other_user.id, 1).destroy
    end
  end
  
  def delete_relationship!(other_user)
    if self.is_student? && other_user.is_teacher? && self.teachers.include?(other_user)
      self.set_not_to_be_friends!(other_user, true)
    end
    if self.is_teacher? && other_user.is_student? && self.students.include?(other_user)
      self.set_not_to_be_friends!(other_user, false) 
    end
  end
  def delete_request!(other_user)
    Request.find_all_by_receiver_id_and_sender_id(other_user.id, self.id).collect {|x| x.destroy}
    Request.find_all_by_receiver_id_and_sender_id(self.id, other_user.id).collect {|x| x.destroy}
  end

  def delete_relationship_and_request!(other_user)
    delete_relationship!(other_user)
    delete_request!(other_user)
  end

  def create_normal_request!(sender_id, kind, content)
    if !self.blocked_users.include?(User.find(sender_id))
      self.requests.create!(sender_id: sender_id, kind: kind, content: content)
    end
  end

  def delete_room_relationship!(other_user, current_student)
    if current_student
      other_user.rooms.each do |room|
        if room.students.include?(self)
          room.room_student_relationships.find_by_student_id(self[:id]).destroy
        end 
      end
    else
      self.rooms.each do |room|
        if room.students.include?(other_user)
          room.room_student_relationships.find_by_student_id(other_user[:id]).destroy
        end
      end
    end
  end
end

app/controllers/admin/users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::UsersController < Admin::ResourcesController
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
#  before_filter :require_signin, only: [:edit, :update, :destroy, :full_role]
  before_filter :correct_user, only: [:edit, :update, :destroy, :full_role, :requests, :friends]
  before_filter :require_signin, only: :correct_user

  def new
    @user = User.new
  end

  def create
    role = (params[:user][:role] == "student")
    params[:user].delete :role
    @user = User.new(params[:user])
    @user.role = (role ? 1 : 0)
    if @user.save
      flash[:success] = "注册成功，请完善个人资料!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    return unless signed_in?
    if Comment.find_by_student_id_and_teacher_id(current_user[:id], @user[:id])
      @has_evaluate = true
    else 
      @has_evaluate = false
    end
    @can_evaluate = (@user.is_teacher? && current_student? && @user.students.include?(current_user))
  end

  def edit
    @user = User.find(params[:id])
    if current_teacher?
      render "edit_teacher"
      return
    end
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:current_password] 
      if @user.authenticate(params[:user][:current_password])
        @user.updating_password = true # RailsCasts #41
        params[:user].delete :current_password
      else
        flash.now[:error] = "当前密码错误"
        render 'edit' and return
      end
    else
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      if current_student?
        render 'edit'
      else
        render 'edit_teacher'
      end
    end
  end

  def full_role
    @user = User.find(params[:id])
    @user.role = 2 #0老师 1学生 2既是老师也是学生
    @user.save!
    redirect_to @user
  end

  def messages
    user = User.find(params[:id])
    @messages = user.received_messages
  end
  
  def friends
    user = User.find(params[:id])
    if current_student?
      @title = "我的导师"
      @relationships = user.relationships
    else
      @title = "我的学生"
      @relationships = user.reverse_relationships
    end
  end

  def requests
    @title = "所有请求"
    @user = User.find(params[:id])
    if current_student?
      @user.requests.find_all_by_kind_and_read([2,4],false).collect do |x| x.update_attributes(read: true) end
      @add_requests = @user.requests.find_all_by_kind(2)
      @other_requests = @user.requests.find_all_by_kind(4)
    else
      @add_requests = @user.requests.find_all_by_kind(1)
      @user.requests.find_all_by_kind_and_read([1,3],false).collect do |x| x.update_attributes(read: true) end
      @other_requests = @user.requests.find_all_by_kind(3)
    end
  end

  def blocked_users
    @user = User.find(params[:id])
    @blocked_users = @user.blocked_users
  end
 
  def my_rooms
    if current_student?
      @title = "我的聊天室"
      @student = User.find(params[:id])
      @rooms = []
      Room.all.each do |room|
        if room.students.include? @student
          @rooms.push(room)
        end
      end
    end
    render 'rooms/index'
  end

  private
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to root_path, notice: "非法操作"
      end
    end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "avatar img-rounded")
  end

  def gender(user)
    return "女" if user.gender == 0
    return "男" if user.gender == 1
    return "未知"
  end

  def role(user)
    return "学生" if user.role == 1
    return "老师" if user.role == 0
    return "既是老师也是学生" if user.role == 2
  end

  def student_visible_to_s(user)
    if user.student_visible
      "想学习" 
    else
      "不想学习"
    end
  end

  def teacher_visible_to_s(user)
    if user.teacher_visible
      "想教学" 
    else
      "不想教学"
    end
  end

  def video_for(id)
   '<embed src="http://player.youku.com/player.php/sid/'+id+'/v.swf" allowFullScreen="true" quality="high" width="480" height="400" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>' 
  end
end

app/views/users/_edit_password.html.erb
<%= form_for(@user) do |f| %>
<table>
	<tr>
		<td><%= f.label :current_password %></td>
		<td><%= f.password_field :current_password %></td>
	</tr>
	<tr>
		<td><%= f.label :password %></td>
		<td><%= f.password_field :password %></td>
	</tr>
	<tr>
		<td><%= f.label :password_confirmation %></td>
		<td><%= f.password_field :password_confirmation %></td>
	</tr>
</table>
  <%= f.submit "修改密码", class: "btn btn_edit" %>
<% end %>

app/views/users/_edit_right.html.erb
<div class="info_right" style="border:none;">
  <div class="upload-head">
    <%= gravatar_for(@user, size: 200) %>
    <br/>
    <%= link_to "编辑头像", "http://cn.gravatar.com/" %>
    <div id="clear"></div>
  </div>
  <div class="psw_rng">
    <a href="javascript:void(0)" id="chng_psw_cmd">修改密码</a>
    <div id="psw_rng" style="display:none;">
      <%= render "edit_password" %>
    </div>
  </div>
</div>
<div id="clear"></div>

app/views/users/_request_form.html.erb
<div id="request_form">
  <% if current_student? && @user.is_teacher? %>
    <% if current_user.following(@user)? %>
    <% end %>
  <% end %>
</div>

app/views/users/_unblocked_form.html.erb
<div class="blocked-user">
  <div class="span3">
    <div class="room-img">
      <%= gravatar_for(user, size: 80) %>
    </div>
    <p><%= link_to user.name, user %></p>
    <%= form_tag(blocked_relationship_path(user.id), method:'delete') do %>
      <%= hidden_field_tag :blocked_user_id, user.id %>
      <p><%= submit_tag "移出黒名单", class: "btn" %></p>
    <% end %>
  </div>
</div>

app/views/users/_user_item.html.erb
<li>
              <%= link_to image_tag("user.png",:border => 0,:alt => '', :title=>''),user %>
              <%= link_to user[:name], user%>
              <%= render 'shared/request_form'%>
            </li>

app/views/users/blocked_users.html.erb
<% provide(:title, "被屏蔽的用户") %>
<%= render 'layouts/sub_header' %>
<div class="room_container">
  <p>被屏蔽的用户不能给您发消息</p>
  <% if @blocked_users.any? %>
    <% @blocked_users.each do |user| %>
      <%= render 'unblocked_form', user: user %>
    <% end %>
  <% else %>
    <p>您还没有屏蔽其他用户</p>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, t("user.edit")) %>
<div class="info_container">
  <div class="page">
    <%= render 'shared/error_messages', object: @user %>
    <div class="info_left" style="border:none;">
	    <%= form_for(@user) do |f| %>
      <table>
        <tr>
          <td><%= f.label :name %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :gender %></td>
          <td><%= f.select :gender, [['男', 1],['女', 0]], include_blank: true %></td>
        </tr>
        <tr>
          <td><%= f.label :degree_id %></td>
          <td><%= f.select :degree_id, degrees, include_blank: true %></td>
        </tr>
        <tr>
          <td><%= f.label :district_id %></td>
          <td><%= f.select :district_id, districts, include_blank: true %></td>
        </tr>
        <tr>
          <td><%= f.label :student_visible %></td>
          <td><%= f.check_box :student_visible %>想让其他用户通过搜索学生找到我</td>
        </tr>
        <tr>
          <td><%= f.label :description %></td>
          <td><%= f.text_area :description, {style: "width:auto;height:100px;"}%></td>
        </tr>
        <tr>
          <td><%= f.label "想学习的科目" %></td>
          <td>
            <div class="choicebox" style="font-size:14px;">
              <% Subject.all.each do |subject| %>
                <div class="choice_cell">
                  <label>
                    <%= check_box_tag("user[student_subject_ids][]", subject.id, @user.student_subject_ids.include?(subject.id)) %>
                    <%= subject.name %>
                  </label>
                <%= hidden_field_tag "user[student_subject_ids][]" %>
                </div>
              <% end %>
			  <div id="clear"/>
            </div>
            <div id="clear"/>
          </td>
        </tr>
      </table>
      <%= f.submit t("common.update"), class: "btn btn_edit" %>
      <% end %>
	  <div id="clear"></div>
      <%= form_tag(full_role_user_path(@user),method: :post) do %>
    	  <%= submit_tag "我也想当老师",  class: "btn btn_edit", confirm: :"你确定吗？" unless current_user.full_role? %>
      <% end %>
    </div>
    <%= render 'edit_right' %>
    
  </div>
</div>
<div id="clear"/>
<script>
$("#chng_psw_cmd").click(function(){ 
 $("#psw_rng").show();
}); 
</script>

app/views/users/edit_teacher.html.erb
<% provide(:title, t("user.edit")) %>
<div class="info_container">
  <div class="page">
    <%= render 'shared/error_messages', object: @user %>
    <div class="info_left" style="border:none;">
	    <%= form_for(@user) do |f| %>
        <table>
          <tr>
            <td><%= f.label :name %></td>
            <td><%= f.text_field :name %></td>
          </tr>
          <tr>
            <td><%= f.label :gender %></td>
            <td> <%= f.select :gender, [['男', 1],['女', 0]], include_blank: true %></td>
          </tr>
          <tr>
            <td><%= f.label :degree_id %></td>
            <td><%= f.select :degree_id, degrees, include_blank: true %></td>
          </tr>
          <tr>
            <td><%= f.label :district_id %></td>
            <td><%= f.select :district_id, districts, include_blank: true %></td>
          </tr>
          <tr>
            <td><%= f.label :teacher_visible %></td>
            <td><%= f.check_box :teacher_visible %>想让其他用户通过搜索老师找到我</td>
          </tr>
          <tr>
            <td><%= f.label :description %></td>
            <td><%= f.text_area :description, {style: "width:auto;height:100px;"}%></td>
          </tr>
          <tr>
            <td><%= f.label :video_id %></td>
            <td><%= f.text_field :video_id %>当前仅支持优酷</td>
          </tr>
          <tr>
            <td><%= f.label "想讲授的科目" %></td>
            <td>
              <div class="choicebox" style="font-size:14px;">
                <% Subject.all.each do |subject| %>
                  <div class="choice_cell">
                    <label>
                      <%= check_box_tag("user[teacher_subject_ids][]", subject.id, @user.teacher_subject_ids.include?(subject.id)) %>
                      <%= subject.name %>
                    </label>
                    <%= hidden_field_tag "user[teacher_subject_ids][]" %>
                  </div>
                <% end %>
				<div id="clear"/>
              </div>
              <div id="clear"/>
            </td>
          </tr>
        </table>
        <%= f.submit t("common.update"), class: "btn btn_edit" %>
	    <% end %>
		<div id="clear"></div>
	    <%= form_tag(full_role_user_path(@user), method: :post) do %>
	  	  <%= submit_tag "我也想当学生",  class: "btn btn_edit", confirm: :"你确定吗？"unless current_user.full_role? %>
      <% end %>
    </div>
    <%= render 'edit_right' %>
    
  </div>
</div>
<div id="clear"/>
<script>
$("#chng_psw_cmd").click(function(){ 
 $("#psw_rng").show();
}); 
</script>

app/views/users/friends.html.erb
<% provide(:title, @title) %>
<%= render 'layouts/sub_header' %>
<div class="room_container">
  <% if @relationships.any? %>
    <% @relationships.each do |r| %>
      <% user = current_student? ? r.teacher : r.student %>
      <div class="span5">
        <div class="room-img">
          <%= gravatar_for(user, size: 80) %>
        </div>
        <p style="margin-top:0px;"><%= link_to user.name, user %></p>
        <p>开始时间：<%= r.created_at.localtime.to_s(:db) %></p>
        <p><%= render 'shared/remove_relationship', user: user %></p>
      </div>
    <% end %>
  <% else %>
    <p>没有找到和您有教学关系的人</p>
  <% end %>
  <div id="clear"></div>
</div>

app/views/users/messages.html.erb
<%= render @messages %>

app/views/users/new.html.erb
<% provide(:title, t("common.register")) %>
<div class="register">
<div class="row" style="background:none;">
  <div class="span6">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
 <table>
          <tr>
            <td><%= f.label :name %></td>
            <td><%= f.text_field :name%></td>
          </tr>
          <tr>
            <td><%= f.label :email %></td>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <td><%= f.label :password %></td>
            <td><%= f.password_field :password%></td>
          </tr>
          <tr>
            <td><%= f.label :password_confirmation %></td>
            <td><%= f.password_field :password_confirmation%></td>
          </tr>
        </table>

      <fieldset>
        <div class="role-select" >
          <%= f.label :role %>
          <%= f.radio_button :role, "teacher"%>
          <%= f.label :role_teacher, "教师" %>
          <%= f.radio_button :role, "student", checked: true %>
          <%= f.label :role_student, "学生" %>
		  <div id="clear"/>
        </div>
      </fieldset>

      <%= f.submit t("common.register"), class: "btn btn-primary" %>
	  <div id="clear"/>
    <% end %>
  </div>
  </div>
</div>

app/views/users/requests.html.erb
<% provide(:title, @title)%>

<div class="row">
  <div class="inline">
	<% if @add_requests.count!= 0||@other_requests.count != 0%>
	  <% if @add_requests%>
	    <% @add_requests.each do |request|%>
	    <li style="float:none; margin-top:10px;">
	    <%=link_to User.find(request.sender_id).name, user_path(User.find(request.sender_id))%>   
	    申请加您好友：<%= request.content%>
	    <%= render 'shared/agree_form', user: User.find(request.sender_id) %>
	    <%= render 'shared/refuse_form', user: User.find(request.sender_id)%>
	    <%= render 'shared/delete_request', request: request%>
		<div id="clear"></div>
	    </li>
	    <% end%>
	  <% end%>
	    
	  <% if @other_requests%>
	    <% @other_requests.each do |request|%>
	      <li>
	      <%= link_to User.find(request.sender_id).name, user_path(User.find(request.sender_id))%>
	      <%= request[:content]%>
          <%= render 'shared/delete_request', request: request%>
	      </li>
	    <% end%>
	  <% end%>
	<% else %>
	          无任何请求或消息
	<% end%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!-- 仅供测试 -->
<% if signed_in? %>
	<div id="myModal" class="modal hide fade">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	    <h4>写下你对 <%=@user.name%> 的评价吧^_^</h4>
	  </div>
	  <div class="modal-body">
	    <% if !@has_evaluate && @can_evaluate%>
	      <% comment = Comment.new(teacher_id: @user[:id], student_id:current_user[:id]) %>
	      <%= render "comments/new", comment: comment%>    
	    <% end%>
	    <% if @has_evaluate && @can_evaluate%>
	      <% comment = Comment.find_by_student_id_and_teacher_id(current_user[:id], @user[:id])%>
	        <%= render "comments/update", comment: comment%>
	        <%= render "comments/destroy", comment: comment%>
	    <% end%>
	  </div>
	</div>
<% end %> 

<div class="info_container" style="border:none;">
  <div class="page" style="float:none;">
      <% if signed_in? && !current_user?(@user) %>
       
          <button class="btn" id="chat-with-button">聊天</button>
      <% end %>
    <table>
      <tr>
        <td><label>在线状态：</label>
          <% if @user.online? %>
            <!-- 下面id用于聊天，请不要删除-->
            <img id="img_online" src="/assets/res/online.png" width="30" height="30"/>
          <% else %>
            <img src="/assets/res/offline.png" width="30" height="30"/>
          <% end %>
          
        </td>
		        <!-- 下面id用于聊天，请不要删除-->
        <td>
          <h1 id="username"><%= @user.name %></h1>
        </td>
        <% if signed_in? %>
          <%= render "shared/request_form", :user => @user %>
        <% end %>
       
        <% if signed_in? && current_user?(@user) %>
          <td>
            <%= link_to "编辑资料", edit_user_path(@user), class: "btn_profile" %>
          </td>
        <% end %>
      </tr>
    </table>
    <div class="info_left" style="border-right:none;">
      <h6>个人信息</h6>
      <ul>
        <li>性别：<%= gender(@user) %> </li>
        <% if @user.district %>
          <li>地区：<%= @user.district.name %></li>
        <% end %>
        <% if @user.degree %>
          <li>学历：<%= @user.degree.name %></li>
        <% end %>
        <li>身份：<%= role(@user) %> </li>
      </ul>
	  
      <% if @user.is_student? %>
        <h6>学习状态</h6>
        <p><%= student_visible_to_s(@user) %></p>
        <h6>想要学习的科目</h6>
        <div class="course">
          <ul>
            <% @user.student_subjects.each do |subject| %>
              <li><%= subject.name %></li>
            <% end %>
            <div id="clear"/>
          </ul>
        </div>
	    <% end %>
	  
      <% if @user.is_teacher? %>
        <h6>教学状态</h6>
        <p><%= teacher_visible_to_s(@user) %></p>
        <h6>想要讲授的科目</h6>
        <div class="course">
          <ul>
            <% @user.teacher_subjects.each do |subject| %>
              <li><%= subject.name %></li>
            <% end %>
            <div id="clear"/>
          </ul>
        </div>
		
        <h6>自我描述</h6>
        <p><%= @user.description %></p>
        <% if @user.is_teacher? %>
          <h6>评价</h6>
            
          <%= render "comments/index", comments: @user.comments %>
        <% end %>
        <% if @can_evaluate %>
          <a href="#myModal" role="button" class="btn" data-toggle="modal">我的评价</a>
        <% end%>
		
        <% unless @user.video_id.blank? %>
          <h6>视频</h6>
          <%= raw video_for(@user.video_id) %>
        <% end %>
      <% end %>
	  
    </div>
    <div class="info_right">
      <%= gravatar_for(@user, size: 200) %> 
     
    </div>
    <div id="clear"/>
  </div>
</div>
<div id="clear"/>

app/views/users/show_blocked_users.html.erb
<% provide(:title, @title)%>
<%= render 'layouts/sub_header' %>
<%if @blocked_users.any?%>
  <% @blocked_users.each do |user|%>
  <li>
  <%= link_to user[:name],user %>
  <%= render 'shared/unblocked_form',user:user%>
  </li>
  <% end %>
<%else%>
<p>无黑名单</p>
<%end%>