config/routes.rb
OnlineTutoringApp::Application.routes.draw do
  resources :annoncements
  resources :advertisements
  root to: "static_pages#home"

  get "static_pages/about"
  resources :users do
    member do
      get :friends, :requests, :blocked_users, :my_rooms
    end
    resources :rooms
  end

  match '/users/:id/messages', to: 'users#messages', via: :get
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :requests, only: [:create, :destroy]
  resources :messages, only: :create
  resources :blocked_relationships, only: [:create,:destroy]
  resources :comments, only: [:create, :update, :destroy]
  
  match '/refresh', to: 'sessions#refresh', via: :get

  match '/signup', to: 'users#new'
  match '/users/:id/full_role', to: 'users#full_role', via: :post, as: :full_role_user
  match '/signin', to: 'sessions#new', via: :get
  match '/signin', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/search', to: 'search_contents#new', as: :new_search
  match '/search_contents', to: 'search_contents#create', via: :get, as: :search
  match '/requests/delete_request', to: 'requests#delete_request', via: :post
  match '/rooms/delete_by_student', to: 'rooms#delete_by_student', via: :post
  match '/rooms/:id/new_line', to: 'rooms#new_line'
  match '/rooms/:id/clear', to: 'rooms#clear'
  match '/rooms/:id/messages', to: 'rooms#message', as: :room_new_message

  match '/chat/users/new', to: 'chat#new_user', via: :get
  match '/chat/users/:id', to: 'chat#remove_user' 
  match '/chat/messages', to: 'chat#get_conversations'
  match '/chat/messages/:id', to: 'chat#get_conversation'
  match '/chat/messages/:id/read', to: 'messages#read', via: :get

end

app/views/shared/_add_friends.html.erb
  <%= form_tag(requests_path, :method=>'post', :multipart => true) do  %>
  <div><%= hidden_field_tag :receiver_id, user.id %></div>
  <div><%= text_field_tag :content %></div>
  <%= submit_tag "加为好友", class: "btn  btn-primary" %>
  <% end %>	

app/views/shared/_agree_form.html.erb
<div id="agree_refuse_form">
<%= form_tag(relationships_path, method:'post') do %>
<%= hidden_field_tag :sender_id,user.id%>
<%= submit_tag "同意", class: "btn btn-primary"%>
<% end %>
</div>

app/views/shared/_blocked_form.html.erb
<%= form_tag(blocked_relationships_path, method:'post') do %>
<%= hidden_field_tag :blocked_user_id, user.id%>
<%= submit_tag "加入黒名单", class: "btn"%>
<% end %>

app/views/shared/_delete_request.html.erb
<%= form_tag(:controller=>"requests", :action=> "delete_request",method:"delete") do%>
<%= hidden_field_tag :request_id, request.id%>
<%= submit_tag "删除", class: "btn btn-primary"%>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<% object.errors.delete(:password_digest) %>
  <div id="error_explanation">
    <div class="alert alert-error">
      这个表单有 <%= object.errors.count %> 个错误
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_refuse_form.html.erb
<%= form_tag(request_path(user), method:'delete', :multipart => true) do%>
<%= hidden_field_tag :sender_id,user.id%>
<%= submit_tag "拒绝", class: "btn btn-primary"%>
<% end%>

app/views/shared/_remove_relationship.html.erb
<%= form_tag(relationship_path(user.id), method:'delete', :multipart => true) do%>
  <%= hidden_field_tag :user_id,user.id%>
  <%= submit_tag "解除关系", class: "btn btn-warning", data: {confirm: '你确定吗？ '}%>
<% end %>

app/views/shared/_request_form.html.erb
<% if !current_user?(user) && user.blocked_users.include?(current_user)%>
他已将你屏蔽
<% else %>
	<% if (current_student? && user.is_teacher? && !current_user?(user)) || (current_teacher? && user.is_student? && !current_user?(user)) %> 
	  <% if current_user.have_been_friends?(user,current_student?) %>
	    <%= render'shared/remove_relationship', :user => user %>
	  <% else %>
	    <% if !current_user.blocked_users.include?(user)%>
	        <a href="#addModal" role="button" class="btn" data-toggle="modal">加为好友</a>
			<div id="addModal" class="modal hide fade">
			  <div class="modal-header">
			    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			    <h4>亲，写下你想加 <%=@user.name%>为好友的原因吧 ^_^</h4>
			  </div>
			  <div class="modal-body">
				<%= render'shared/add_friends', :user => user%>
			  </div>
			</div>
	  	<% end %>
	  <% end %>
	<% end %>
<% end %>
<% if !current_user?(user) %>
  <% if current_user.blocked_users.include?(user) %>
  <%= render 'shared/unblocked_form', :user => user %>
  <% else %>
  <%= render 'shared/blocked_form', :user => user %>
  <% end %>
<% end %>

app/views/shared/_search_form.html.erb
<div class="row"> 
  <div class="span6 offset3">
    <%= form_for(:search_content, url: search_contents_path) do |f| %>
    <%= f.text_field :content, :value => @content %>
    <%= f.submit "搜索", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_sub_header.html.erb
<div class="clearfix">
  <ul>
    <% if current_student? %>
      <li><%= link_to "我的导师", friends_user_path(current_user) %> </li>
    <% elsif current_teacher? %>
      <li><%= link_to "我的学生", friends_user_path(current_user) %> </li>
    <% end %>
    <li><%= link_to "黑名单", blocked_users_user_path(current_user) %></li>
    <li>讨论组</li>
  </ul>
</div>

app/views/shared/_unblocked_form.html.erb
<div class="blocked-user">
  <div class="span3">
    <%= form_tag(blocked_relationship_path(user.id), method:'delete') do %>
      <%= hidden_field_tag :blocked_user_id,user.id%>
	  <div style="margin-left:-20px;">
      <%= submit_tag "移出黒名单", class: "btn"%>
    <% end %>
  </div>
</div>

app/views/shared/_user.html.erb
<li>
              <%= link_to image_tag("user.png",:border => 0,:alt => '', :title=>''),user %>
              <%= link_to user[:name], user%>
              <% #render 'shared/request_form', :user => user%>
            </li>