config/routes.rb
OnlineTutoringApp::Application.routes.draw do
  resources :annoncements
  resources :advertisements
  root to: "static_pages#home"

  get "static_pages/about"
  resources :users do
    member do
      get :friends, :requests, :blocked_users, :my_rooms
    end
    resources :rooms
  end

  match '/users/:id/messages', to: 'users#messages', via: :get
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :requests, only: [:create, :destroy]
  resources :messages, only: :create
  resources :blocked_relationships, only: [:create,:destroy]
  resources :comments, only: [:create, :update, :destroy]
  
  match '/refresh', to: 'sessions#refresh', via: :get

  match '/signup', to: 'users#new'
  match '/users/:id/full_role', to: 'users#full_role', via: :post, as: :full_role_user
  match '/signin', to: 'sessions#new', via: :get
  match '/signin', to: 'sessions#create', via: :post
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/search', to: 'search_contents#new', as: :new_search
  match '/search_contents', to: 'search_contents#create', via: :get, as: :search
  match '/requests/delete_request', to: 'requests#delete_request', via: :post
  match '/rooms/delete_by_student', to: 'rooms#delete_by_student', via: :post
  match '/rooms/:id/new_line', to: 'rooms#new_line'
  match '/rooms/:id/clear', to: 'rooms#clear'
  match '/rooms/:id/messages', to: 'rooms#message', as: :room_new_message

  match '/chat/users/new', to: 'chat#new_user', via: :get
  match '/chat/users/:id', to: 'chat#remove_user' 
  match '/chat/messages', to: 'chat#get_conversations'
  match '/chat/messages/:id', to: 'chat#get_conversation'
  match '/chat/messages/:id/read', to: 'messages#read', via: :get

end

app/models/room.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  outline    :string(255)
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# -*- encoding : utf-8 -*-
class Room < ActiveRecord::Base
  attr_accessible :outline, :user_id
  belongs_to :user
  has_many :room_student_relationships, dependent: :destroy
  has_many :students, through: :room_student_relationships

  validates :user_id, presence: true

  # 房间的所有人员
  def users
    # 一定要dup, 否则就会修改数据库
    self.students.dup << self.user
  end
end

app/controllers/admin/rooms_controller.rb
# -*- encoding : utf-8 -*-
class Admin::RoomsController < Admin::ResourcesController
end

app/controllers/rooms_controller.rb
# -*- encoding : utf-8 -*-
class RoomsController < ApplicationController
  before_filter :require_signin
  before_filter :members_in_room, only: [:show, :message]
  before_filter :correct_user, only: [:new, :index, :create, :update, :edit, :destroy]
  before_filter :room_owner, only: [:new_line, :clear]
  # post 时无需authentication token
  protect_from_forgery except: :new_line
#  before_filter :require_current_teacher,only:[:new, :index, :create,:update,:edit,:destroy]

  def new
    @room = @user.rooms.new
    @student_selected = []
    self.get_student
    @outline = nil
  end

  def index
    @rooms = @user.rooms
  end
  
  def show
    @room = Room.find(params[:id])
    @students = @room.students
  end

  def update
    @room = @user.rooms.find(params[:id])
    if params[:outline].blank?
      flash[:error] = "标题内容不能为空"
      redirect_to edit_user_room_path(current_user,params[:id]) and return 
    end
    @room.update_attributes(outline: params[:outline])
    @student_selected = []
    if params[:student]
      params[:student].each do |student_id|
        @student_selected.push(Integer(student_id))
      end
    end
    @room.room_student_relationships.each do |relationship|            
      if @student_selected.include?relationship[:student_id]
        # do nothing
      else
         if @user.students.include?(User.find(relationship[:student_id]))  
           #提醒被老师移出聊天室的学生
           User.find(relationship[:student_id]).create_normal_request!(@user[:id], 4, "将你移出了 "+ @room[:outline] + " 聊天室")
         end
         @room.room_student_relationships.find(relationship[:id]).destroy 
      end
    end
    @student_selected.each do |student_id|                            
      if @room.room_student_relationships.find_by_student_id(student_id)
        # do nothing
      else
        if @user.students.include?(User.find(student_id))
          # 提醒被老师 加入聊天室的学生
          @room.room_student_relationships.create!(student_id: student_id)  
          User.find(student_id).create_normal_request!(@user[:id], 4, "将你加入到了 " + @room[:outline] + " 聊天室中"+ "聊天室的简单介绍如下： #{params[:information]}")
        end
      end
    end
    redirect_to user_room_path(current_user, @room[:id])
  end

  def create
    if params[:outline].blank?
      flash[:error] = "标题内容不能为空"
      redirect_to new_user_room_path(current_user) and return 
    end
    @room = @user.rooms.create!(outline: params[:outline])
    @student_selected = []
    if params[:student]
      params[:student].each do |single_student_id|
        @student_selected.push(Integer(single_student_id))
        student = User.find(single_student_id)
        if @user.students.include?(student)
          # 提醒被老师 加入聊天室的学生
          @room.room_student_relationships.create!(student_id: single_student_id) 
          student.create_normal_request!(@user[:id], 4, "将你加入到了 #{@room[:outline]} 聊天室中, 聊天室的简单介绍如下： #{params[:information]}")
        end
      end
    end
    flash[:success] = "创建成功"
    redirect_to user_room_path(current_user, @room)
  end

  def edit
    @room = @user.rooms.find(params[:id])
    @outline = @room[:outline]
    @student_selected = []
    @students = @room.students
    @students.each do |student|
      @student_selected.push(Integer(student[:id]))
    end
    self.get_student
  end

  def destroy
    @room = Room.find(params[:id])
    @room.students.each do |student|
      if @user.students.include?(student)
        student.create_normal_request!(current_user[:id], 4, "解散了 "+@room[:outline]+" 聊天室")
      end
    end
    @user.rooms.find(params[:id]).destroy
    redirect_to user_rooms_path(@user)
  end
  
  # 学生自主退出聊天室
  def delete_by_student 
    @room = Room.find(params[:id])
    if current_student? && current_user.my_rooms.include?(@room)
      current_user.room_student_relationships.find_by_room_id(params[:id]).destroy
      flash[:success] = "成功退出聊天室"
    end
    redirect_to my_rooms_user_path(current_user)
  end
  
  def correct_user
    @user = User.find(params[:user_id])
    unless current_user?(@user)
      redirect_to root_path
    end
  end
  
  #获取当前用户的学生，并且增加一属性 checked 表示 是否被加入到聊天室
  def get_student
    @students = current_user.students
    @students.collect do |student|
      student[:checked] = @student_selected.include?(student[:id])
    end
  end
  
  #判断用户是否属于该聊天室
  def members_in_room
    room = Room.find(params[:id])
    #是该聊天室的老师
    if current_teacher? && current_user.rooms.include?(room)
    #是该聊天室的学生
    elsif current_student? && room.students.include?(current_user)
    else
      flash[:error] = "你没有权限"
      redirect_to current_user
    end
  end

  # 画了一条线（用于白板）
  def new_line
    PrivatePub.publish_to("/rooms/#{params[:id]}",
                          points: params[:points].values,
                          color: params[:color],
                          lineWidth: params[:lineWidth])
    render nothing: true
  end

  # 清除白板上画的内容
  def clear
    PrivatePub.publish_to("/rooms/#{params[:id]}", type: "clear")
    render nothing: true
  end

  # 只有房主才能同步白板内容给其他人
  def room_owner
    room = Room.find(params[:id])
    redirect_to root_path unless current_user?(room.user)
  end

  # 讨论组里发的消息
  def message
    message = {
      message: {
        content: ERB::Util.html_escape(params[:message][:content]),
        created_at: Time.now.to_s(:db),
        sender_id: current_user.id,
        sender_name: current_user.name
      },
      type: "message"
    }
    PrivatePub.publish_to("/rooms/#{params[:id]}", message)
    render nothing: true
  end
end

app/helpers/rooms_helper.rb
# -*- encoding : utf-8 -*-
module RoomsHelper
  def members_in_room
    user_id = params[:user_id]
    room_id = params[:id]
    if current_user?(User.find(user_id)) && current_teacher? && current_user.rooms.include?(Room.find(room_id))
    
    elsif !current_user?(User.find(user_id)) && current_student? && Room.find(room_id).students.include?(User.find(user_id))
    else
      flash[:error] = "you don't have access"
      redirect_to current_user
    end
  end

end

app/views/rooms/_canvas.html.erb
<% if current_teacher? %>
  <div style="margin-bottom:10px;">
    <button class="btn_color" style="background:url(/assets/res/trash.png); background-size: 100%;" onclick="clearAndUpdate()"></button>
    <button class="btn_color" style="background:url(/assets/res/red.png); background-size: 100%;" onclick="color='ff0000'"></button>
    <button class="btn_color" style="background:url(/assets/res/green.png); background-size: 100%;" onclick="color='00ff00'"></button>
    <button class="btn_color" style="background:url(/assets/res/blue.png); background-size: 100%;" onclick="color='0000ff'"></button>
    <button class="btn_color" style="background:url(/assets/res/black.png); background-size: 100%;" onclick="color='000000'"></button>
    <button class="btn_color" style="background:url(/assets/res/thin.png); background-size: 100%;" onclick="lineWidth=1"></button>
    <button class="btn_color" style="background:url(/assets/res/medium.png); background-size: 100%;" onclick="lineWidth=4"></button>
    <button class="btn_color" style="background:url(/assets/res/thick.png); background-size: 100%;" onclick="lineWidth=8"></button>
  </div>
<% end %>
<canvas id="chatroom-canvas" draggable="false" width="836" height="400">
</canvas>

app/views/rooms/_delete_room.html.erb
<%= form_tag(user_room_path(@room.user, room[:id]), method: 'delete') do%>
<%= hidden_field_tag :id, room[:id]%>
<div style="float:right;">
<%= submit_tag "删除聊天室",class: "btn btn-danger"%>
</div>
<% end%>

app/views/rooms/_quit_room.html.erb
<%= form_tag(rooms_delete_by_student_path, method: 'post') do %>
<%= hidden_field_tag :id, room.id %>
<div style="float:right;">
<%= submit_tag "退出讨论组", class: "btn btn-warning" %>
</div>
<% end%>

app/views/rooms/_room.html.erb
<div class="blocked-user">
  <div class="span5">
    <div class="room-img">
      <%= gravatar_for(room.user, size: 80) %>
    </div>
    <%= link_to room.outline, user_room_path(room.user, room.id)%>
    <p>导师：<%= link_to room.user.name, room.user %></p>
</div>

app/views/rooms/edit.html.erb
<% provide(:title,"编辑聊天室") %>
<div class="row" style="background:none;">
  <div class="span5">
      <%= form_tag(user_room_path(current_user,@room[:id]), method: 'put') do %>
	  <%= label_tag "聊天室主题"%>
	  <%= text_field_tag :outline, @outline%>
      <%= label_tag :information, "讨论组的简单介绍以及讲课时间等基本情况（会发给学生）",style:"width:230px;"%>
      <%= text_field_tag :information%>
	  <div id="clear"></div>
	  <table>
		<tr><td><label>成员</label></td></tr>
        <% @students.each do |student|%>
          <tr>
			  <td></td>
			  <td width="20px"><%= check_box_tag 'student[]', student[:id],student[:checked]%></td>
			  <td>
          <%= label_tag student[:name]%></td></tr>
        <% end%>
		</table>
		
		 <%= submit_tag "更新聊天室", class: "btn btn-primary"%>
		 <div id="clear"></div>
      <% end%>
  
 
  </div>
</div>

app/views/rooms/index.html.erb
<%= render 'layouts/sub_header' %>
<div class="room_container">
  <% if signed_in? && current_teacher? %>
    <div class="create_room"><%= link_to "创建讨论组", new_user_room_path(current_user) %></div>
  <% end %>
  <div>
    <% if signed_in? %>
      <%= render @rooms %>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<% provide(:title, "创建讨论组") %>
<div class="row" style="background:none;">
  <div class="background new-chatroom span10" style="padding-bottom:50px;">
    <%= form_tag(user_rooms_path, method: 'post') do %>
      <%= label_tag :outline, "讨论组主题" %>
      <%= text_field_tag :outline, @outline%>
      <%= label_tag :information, "讨论组的简单介绍以及讲课时间等基本情况（会发给学生）" %>
      <%= text_field_tag :information%>
      </br>
      允许进入的学生
      <ul>
        <% @students.each do |student|%>
          <li>
          <label>
            <%= check_box_tag 'student[]', student.id, student.checked %>
            <%= student.name %>
          </label>
          </li>
        <% end%>
      </ul>
        <%= submit_tag "创建讨论组", class: "btn btn-primary" %>

      <% end%>
	  <div id="clear"></div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="background">
  <h1 style="float:left;padding-left:0px;padding-bottom:10px;"><%= @room[:outline] %></h1>
  <% if @room.user == current_user && current_teacher?%>
    <%= render 'delete_room', room: @room%>
  <% end%>

  <% if current_student? && current_user.my_rooms.include?(@room)%>
    <%= render 'quit_room', room: @room%>
  <% end %>
  <div id="clear"></div>
  <%= render 'canvas' %>
  <div id="chatroom-userlist">
	  <div class="rolelist">
	  <img src="/assets/res/teachericon.png" width="25px">
    <%=link_to "#{@room.user.name}", user_path(@room.user.id)%>
	<div class="roleline"></div>
    <ul id="chatroom-student-list">
    <% @students.each do |student| %>
      <li id=<%= student.id %>>
        <% if student.online? %>
          <span class="chatroom-status chatroom-online"></span>
        <% else %> 
          <span class="chatroom-status chatroom-offline"></span>
        <% end %>
        <%= link_to student.name, user_path(student.id) %>
      </li>
	  
    <% end%>
    </ul>
	  <% if @room.user == current_user && current_teacher?%>
	    <%= link_to "添加或者移除学生", edit_user_room_path(current_user, @room)%>
	  <% end%>
</div>
  </div>
  <div id="chatroom-dialogue-list">
  </div>
  
  <div id="chatroom-sendbox">
    <%= form_for :message, url: room_new_message_path, remote: true do |f| %>
      <%= f.text_area :content, rows: 4 %>
      <%= f.submit "发送",class:"btn",id: "chatroom-sendbutton" %>
    <% end %>
  </div>
</div>